### PR TITLE
Temperature-Converter (Work via CLI)

### PR DESCRIPTION
**Pull request by Deepu2002d**

### CODE REVIEW

**Comment by piyushgoyal1620** [comment]
Hi there,
don't worry!!! I am accepting your PR right now ...
and I know that you are new on it ... don't worry take it easy ... keep learning and one day you will get success... 
I also have material for you go right now and keep this ... good luck ...
no doubt!!!! you are a very good coder, learning is a very important thing in our life at any stage so go through below link and registered and enjoy the content of this site, you will click on this link if you feel comfortable ...

https://www.interviewbit.com/invite/dhbdaab

ThankYou 
Happy / learning...

**Comment by Deepu2002d** [comment]
Thank you.

**Comment by Deepu2002d** [comment]
Hello, here's a request.
Please add hacktoberfest-accepted tag on my committed file.

**Comment by piyushgoyal1620** [comment]
Hi Dear,
i have already master merge your PR. now its time to wait for accepting by hacktoberFest technical team to accept your PR is valid ... this is not my hand to tag your file by any tag its fully depends upon hacktoberFest team... so don't worry ... send some more PR's for another coders and wait for then to merge in master merge ... i have already done my duty at my side ... don't worry ... keep editing good coders file and then send PR's ..

Good Luck !!!
happy Learning...

**Comment by Deepu2002d** [comment]
Actually, I didn't see the hacktoberfest tag on your repo that's why I am asking for it. And even in my profile on hacktoberfest site, they are showing this repo as invalid, I mean not participating. So, that's why I was saying to add hacktoberfest-accepted tag on my file because only owner of repo can do .  :-)

**Pull request merged**
